/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author ADMIN
 */
public class Jpanel_ThongKeDVUaThich extends javax.swing.JPanel {

    /**
     * Creates new form ThongKeDVUaThich
     */
    public Jpanel_ThongKeDVUaThich() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDSDVUaThich = new javax.swing.JPanel();
        pnlThongSoThongKe = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDVUaThich = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1250, 750));

        pnlDSDVUaThich.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh Sách Dịch Vụ Ưa Thích"));

        pnlThongSoThongKe.setBackground(new java.awt.Color(204, 204, 204));
        pnlThongSoThongKe.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Thông Số Thống Kê"));

        javax.swing.GroupLayout pnlThongSoThongKeLayout = new javax.swing.GroupLayout(pnlThongSoThongKe);
        pnlThongSoThongKe.setLayout(pnlThongSoThongKeLayout);
        pnlThongSoThongKeLayout.setHorizontalGroup(
            pnlThongSoThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlThongSoThongKeLayout.setVerticalGroup(
            pnlThongSoThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 132, Short.MAX_VALUE)
        );

        tblDVUaThich.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Dịch Vụ ", "Tên Dịch Vụ", "Giá Dịch Vụ ", "Trạng Thái ", "Số Lượng Khách Hàng Sử Dụng", "Tỷ Lệ Khách Hàng Sử Dụng", "Ghi Chú"
            }
        ));
        tblDVUaThich.setShowGrid(true);
        jScrollPane1.setViewportView(tblDVUaThich);

        javax.swing.GroupLayout pnlDSDVUaThichLayout = new javax.swing.GroupLayout(pnlDSDVUaThich);
        pnlDSDVUaThichLayout.setHorizontalGroup(
        	pnlDSDVUaThichLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(pnlDSDVUaThichLayout.createSequentialGroup()
        			.addGap(18)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 1135, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        		.addComponent(pnlThongSoThongKe, GroupLayout.DEFAULT_SIZE, 1210, Short.MAX_VALUE)
        );
        pnlDSDVUaThichLayout.setVerticalGroup(
        	pnlDSDVUaThichLayout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, pnlDSDVUaThichLayout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 519, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addComponent(pnlThongSoThongKe, GroupLayout.PREFERRED_SIZE, 138, GroupLayout.PREFERRED_SIZE)
        			.addGap(26))
        );
        pnlDSDVUaThich.setLayout(pnlDSDVUaThichLayout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(18)
        			.addComponent(pnlDSDVUaThich, GroupLayout.PREFERRED_SIZE, 1198, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(pnlDSDVUaThich, GroupLayout.PREFERRED_SIZE, 711, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(29, Short.MAX_VALUE))
        );
        this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlDSDVUaThich;
    private javax.swing.JPanel pnlThongSoThongKe;
    private javax.swing.JTable tblDVUaThich;
    // End of variables declaration//GEN-END:variables
}
