/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author ADMIN
 */
public class JPanel_ThongKeKHTiemNang extends javax.swing.JPanel {

    /**
     * Creates new form ThongKeKhachHangTiemNang
     */
    public JPanel_ThongKeKHTiemNang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlKHTiemNang = new javax.swing.JPanel();
        pnlThongSoThongKe = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKHTiemNang = new javax.swing.JTable();

        jPanel1.setPreferredSize(new java.awt.Dimension(1250, 750));

        pnlKHTiemNang.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh Sách Khách Hàng Tiềm Năng"));

        pnlThongSoThongKe.setBackground(new java.awt.Color(204, 204, 204));
        pnlThongSoThongKe.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Thông Số Thống Kê"));

        javax.swing.GroupLayout pnlThongSoThongKeLayout = new javax.swing.GroupLayout(pnlThongSoThongKe);
        pnlThongSoThongKe.setLayout(pnlThongSoThongKeLayout);
        pnlThongSoThongKeLayout.setHorizontalGroup(
            pnlThongSoThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlThongSoThongKeLayout.setVerticalGroup(
            pnlThongSoThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 132, Short.MAX_VALUE)
        );

        tblKHTiemNang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
//                {null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Khách Hàng", "Tên Khách Hàng ", "Số Điện Thoại ", "Ngày Tạo ", "Ngày Cập Nhật ", "Thời Gian Sử Dụng ", "Số Phòng Sử Dụng", "Thành Tiền ", "Ghi Chú"
            }
        ));
        tblKHTiemNang.setShowGrid(true);
        jScrollPane1.setViewportView(tblKHTiemNang);

        javax.swing.GroupLayout pnlKHTiemNangLayout = new javax.swing.GroupLayout(pnlKHTiemNang);
        pnlKHTiemNangLayout.setHorizontalGroup(
        	pnlKHTiemNangLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(pnlKHTiemNangLayout.createSequentialGroup()
        			.addGroup(pnlKHTiemNangLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(pnlKHTiemNangLayout.createSequentialGroup()
        					.addGap(18)
        					.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 1110, GroupLayout.PREFERRED_SIZE))
        				.addComponent(pnlThongSoThongKe, GroupLayout.PREFERRED_SIZE, 1158, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlKHTiemNangLayout.setVerticalGroup(
        	pnlKHTiemNangLayout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, pnlKHTiemNangLayout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 519, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(pnlThongSoThongKe, GroupLayout.PREFERRED_SIZE, 128, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(26, Short.MAX_VALUE))
        );
        pnlKHTiemNang.setLayout(pnlKHTiemNangLayout);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(18)
        			.addComponent(pnlKHTiemNang, GroupLayout.PREFERRED_SIZE, 1170, Short.MAX_VALUE)
        			.addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(pnlKHTiemNang, GroupLayout.PREFERRED_SIZE, 701, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 1196, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 765, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlKHTiemNang;
    private javax.swing.JPanel pnlThongSoThongKe;
    private javax.swing.JTable tblKHTiemNang;
    // End of variables declaration//GEN-END:variables
}
